import { 
  Patient, 
  Doctor, 
  Room, 
  Appointment, 
  EmergencyCase 
} from '@/lib/types';

// Mock Patients Data
export const patients: Patient[] = [
  {
    id: 'P001',
    name: 'John Doe',
    dateOfBirth: '1980-05-15',
    gender: 'male',
    contactNumber: '(555) 123-4567',
    email: 'john.doe@example.com',
    address: '123 Main St, Anytown, USA',
    insuranceProvider: 'Blue Cross',
    insuranceNumber: 'BC12345678',
    medicalHistory: ['Hypertension', 'Type 2 Diabetes'],
    medications: ['Lisinopril', 'Metformin'],
    allergies: ['Penicillin'],
    riskScore: 0.35,
    lastVisit: '2023-12-10',
  },
  {
    id: 'P002',
    name: 'Jane Smith',
    dateOfBirth: '1992-08-22',
    gender: 'female',
    contactNumber: '(555) 987-6543',
    email: 'jane.smith@example.com',
    address: '456 Oak Ave, Somewhere, USA',
    insuranceProvider: 'Aetna',
    insuranceNumber: 'AE87654321',
    medicalHistory: ['Asthma'],
    medications: ['Albuterol'],
    allergies: ['Dust', 'Pollen'],
    riskScore: 0.25,
    lastVisit: '2024-01-05',
  },
  {
    id: 'P003',
    name: 'Robert Johnson',
    dateOfBirth: '1975-03-30',
    gender: 'male',
    contactNumber: '(555) 456-7890',
    email: 'robert.j@example.com',
    address: '789 Pine Rd, Elsewhere, USA',
    insuranceProvider: 'Medicare',
    insuranceNumber: 'MC98765432',
    medicalHistory: ['Coronary Artery Disease', 'Hyperlipidemia'],
    medications: ['Atorvastatin', 'Aspirin'],
    allergies: [],
    riskScore: 0.65,
    lastVisit: '2023-11-28',
  },
  {
    id: 'P004',
    name: 'Maria Garcia',
    dateOfBirth: '1988-12-03',
    gender: 'female',
    contactNumber: '(555) 234-5678',
    email: 'maria.g@example.com',
    address: '321 Elm St, Nowhere, USA',
    insuranceProvider: 'United Healthcare',
    insuranceNumber: 'UH24681357',
    medicalHistory: ['Migraine'],
    medications: ['Sumatriptan'],
    allergies: ['Shellfish'],
    riskScore: 0.15,
    lastVisit: '2024-02-15',
  },
  {
    id: 'P005',
    name: 'David Wilson',
    dateOfBirth: '1965-07-18',
    gender: 'male',
    contactNumber: '(555) 876-5432',
    email: 'david.w@example.com',
    address: '654 Maple Dr, Anytown, USA',
    insuranceProvider: 'Cigna',
    insuranceNumber: 'CI13579246',
    medicalHistory: ['COPD', 'Hypertension'],
    medications: ['Tiotropium', 'Amlodipine'],
    allergies: ['Sulfa drugs'],
    riskScore: 0.70,
    lastVisit: '2023-10-20',
  },
];

// Mock Doctors Data
export const doctors: Doctor[] = [
  {
    id: 'D001',
    name: 'Dr. Sarah Johnson',
    specialty: 'Cardiology',
    qualification: 'MD, Cardiology',
    licenseNumber: 'MD12345',
    contactNumber: '(555) 111-2222',
    email: 'sarah.johnson@hospital.com',
    availability: [
      { day: 'monday', startTime: '09:00', endTime: '17:00' },
      { day: 'wednesday', startTime: '09:00', endTime: '17:00' },
      { day: 'friday', startTime: '09:00', endTime: '13:00' },
    ],
    department: 'Cardiology',
    joinDate: '2018-03-15',
    rating: 4.8,
    performanceMetrics: {
      patientsSeen: 156,
      averageRating: 4.8,
      appointmentCompletionRate: 0.97,
      averageAppointmentDuration: 25,
    },
  },
  {
    id: 'D002',
    name: 'Dr. Michael Chen',
    specialty: 'Neurology',
    qualification: 'MD, PhD, Neurology',
    licenseNumber: 'MD54321',
    contactNumber: '(555) 222-3333',
    email: 'michael.chen@hospital.com',
    availability: [
      { day: 'monday', startTime: '10:00', endTime: '18:00' },
      { day: 'thursday', startTime: '10:00', endTime: '18:00' },
    ],
    department: 'Neurology',
    joinDate: '2015-07-10',
    rating: 4.7,
    performanceMetrics: {
      patientsSeen: 132,
      averageRating: 4.7,
      appointmentCompletionRate: 0.95,
      averageAppointmentDuration: 35,
    },
  },
  {
    id: 'D003',
    name: 'Dr. Emily Rodriguez',
    specialty: 'Pediatrics',
    qualification: 'MD, Pediatrics',
    licenseNumber: 'MD67890',
    contactNumber: '(555) 333-4444',
    email: 'emily.r@hospital.com',
    availability: [
      { day: 'tuesday', startTime: '08:00', endTime: '16:00' },
      { day: 'wednesday', startTime: '08:00', endTime: '16:00' },
      { day: 'thursday', startTime: '08:00', endTime: '16:00' },
    ],
    department: 'Pediatrics',
    joinDate: '2019-01-22',
    rating: 4.9,
    performanceMetrics: {
      patientsSeen: 189,
      averageRating: 4.9,
      appointmentCompletionRate: 0.99,
      averageAppointmentDuration: 20,
    },
  },
  {
    id: 'D004',
    name: 'Dr. James Williams',
    specialty: 'Orthopedics',
    qualification: 'MD, Orthopedic Surgery',
    licenseNumber: 'MD24680',
    contactNumber: '(555) 444-5555',
    email: 'james.w@hospital.com',
    availability: [
      { day: 'monday', startTime: '08:00', endTime: '14:00' },
      { day: 'tuesday', startTime: '08:00', endTime: '14:00' },
      { day: 'friday', startTime: '08:00', endTime: '14:00' },
    ],
    department: 'Orthopedics',
    joinDate: '2017-09-05',
    rating: 4.6,
    performanceMetrics: {
      patientsSeen: 145,
      averageRating: 4.6,
      appointmentCompletionRate: 0.94,
      averageAppointmentDuration: 30,
    },
  },
  {
    id: 'D005',
    name: 'Dr. Lisa Thompson',
    specialty: 'Dermatology',
    qualification: 'MD, Dermatology',
    licenseNumber: 'MD13579',
    contactNumber: '(555) 555-6666',
    email: 'lisa.t@hospital.com',
    availability: [
      { day: 'wednesday', startTime: '09:00', endTime: '17:00' },
      { day: 'thursday', startTime: '09:00', endTime: '17:00' },
      { day: 'friday', startTime: '09:00', endTime: '17:00' },
    ],
    department: 'Dermatology',
    joinDate: '2020-02-28',
    rating: 4.5,
    performanceMetrics: {
      patientsSeen: 168,
      averageRating: 4.5,
      appointmentCompletionRate: 0.96,
      averageAppointmentDuration: 15,
    },
  },
];

// Mock Rooms Data
export const rooms: Room[] = [
  {
    id: 'R001',
    number: '101',
    type: 'Examination',
    floor: 1,
    capacity: 1,
    status: 'available',
    equipment: ['Basic examination tools', 'Computer'],
  },
  {
    id: 'R002',
    number: '102',
    type: 'Examination',
    floor: 1,
    capacity: 1,
    status: 'occupied',
    equipment: ['Basic examination tools', 'Computer'],
    currentPatient: 'P002',
  },
  {
    id: 'R003',
    number: '201',
    type: 'OR',
    floor: 2,
    capacity: 5,
    status: 'reserved',
    equipment: ['Surgical tools', 'Anesthesia machine', 'Vital monitors'],
  },
  {
    id: 'R004',
    number: '301',
    type: 'ICU',
    floor: 3,
    capacity: 1,
    status: 'occupied',
    equipment: ['Ventilator', 'Advanced monitoring', 'Emergency cart'],
    currentPatient: 'P005',
  },
  {
    id: 'R005',
    number: '401',
    type: 'General Ward',
    floor: 4,
    capacity: 2,
    status: 'available',
    equipment: ['Hospital beds', 'Basic monitoring'],
  },
  {
    id: 'R006',
    number: '402',
    type: 'General Ward',
    floor: 4,
    capacity: 2,
    status: 'available',
    equipment: ['Hospital beds', 'Basic monitoring'],
  },
  {
    id: 'R007',
    number: '202',
    type: 'Recovery',
    floor: 2,
    capacity: 3,
    status: 'maintenance',
    equipment: ['Recovery beds', 'Monitoring equipment'],
  },
];

// Mock Appointments Data
export const appointments: Appointment[] = [
  {
    id: 'A001',
    patientId: 'P001',
    doctorId: 'D001',
    roomId: 'R001',
    date: '2024-03-25',
    startTime: '10:00',
    endTime: '10:30',
    type: 'follow-up',
    status: 'scheduled',
    notes: 'Follow-up for hypertension management',
    priority: 'normal',
  },
  {
    id: 'A002',
    patientId: 'P002',
    doctorId: 'D003',
    roomId: 'R002',
    date: '2024-03-25',
    startTime: '09:00',
    endTime: '09:30',
    type: 'consultation',
    status: 'confirmed',
    priority: 'normal',
  },
  {
    id: 'A003',
    patientId: 'P003',
    doctorId: 'D001',
    roomId: 'R001',
    date: '2024-03-26',
    startTime: '11:00',
    endTime: '11:30',
    type: 'follow-up',
    status: 'scheduled',
    notes: 'Cardiac checkup',
    priority: 'high',
  },
  {
    id: 'A004',
    patientId: 'P004',
    doctorId: 'D002',
    roomId: 'R001',
    date: '2024-03-27',
    startTime: '14:00',
    endTime: '14:45',
    type: 'consultation',
    status: 'scheduled',
    notes: 'New patient consultation for migraines',
    priority: 'normal',
  },
  {
    id: 'A005',
    patientId: 'P005',
    doctorId: 'D001',
    roomId: 'R003',
    date: '2024-03-28',
    startTime: '09:00',
    endTime: '11:00',
    type: 'procedure',
    status: 'scheduled',
    notes: 'Cardiac catheterization',
    priority: 'high',
  },
];

// Mock Emergency Cases Data
export const emergencyCases: EmergencyCase[] = [
  {
    id: 'E001',
    patientId: 'P001',
    patientName: 'John Doe',
    arrivalTime: '2024-03-25T08:30:00',
    condition: 'Chest pain',
    severity: 'critical',
    status: 'in-treatment',
    assignedDoctor: 'D001',
    assignedRoom: 'R004',
    vitalSigns: {
      bloodPressure: '160/95',
      heartRate: 110,
      respiratoryRate: 24,
      temperature: 37.2,
      oxygenSaturation: 94,
    },
    treatmentNotes: 'Suspected myocardial infarction. Started on oxygen, aspirin, and nitroglycerin.',
  },
  {
    id: 'E002',
    patientName: 'Unknown',
    arrivalTime: '2024-03-25T09:15:00',
    condition: 'Multiple trauma from car accident',
    severity: 'critical',
    status: 'waiting',
    vitalSigns: {
      bloodPressure: '90/60',
      heartRate: 130,
      respiratoryRate: 28,
      temperature: 36.5,
      oxygenSaturation: 92,
    },
  },
  {
    id: 'E003',
    patientId: 'P004',
    patientName: 'Maria Garcia',
    arrivalTime: '2024-03-25T10:00:00',
    condition: 'Severe migraine',
    severity: 'moderate',
    status: 'waiting',
    vitalSigns: {
      bloodPressure: '130/85',
      heartRate: 88,
      respiratoryRate: 18,
      temperature: 36.8,
      oxygenSaturation: 99,
    },
  },
  {
    id: 'E004',
    patientName: 'Child, approx 5yo',
    arrivalTime: '2024-03-25T10:30:00',
    condition: 'High fever, suspected meningitis',
    severity: 'severe',
    status: 'waiting',
    vitalSigns: {
      temperature: 40.1,
      heartRate: 140,
      respiratoryRate: 30,
    },
  },
];

// Mock Statistics for Dashboard
export const statistics = {
  patientsCount: 1254,
  doctorsCount: 87,
  appointmentsToday: 156,
  roomsAvailable: 23,
  emergencyCases: 8,
  averageWaitTime: 24, // minutes
  bedOccupancyRate: 76, // percentage
  patientsByDepartment: [
    { department: 'Cardiology', count: 342 },
    { department: 'Neurology', count: 198 },
    { department: 'Pediatrics', count: 287 },
    { department: 'Orthopedics', count: 234 },
    { department: 'Dermatology', count: 193 },
  ],
  appointmentsByType: [
    { type: 'Consultation', count: 210 },
    { type: 'Follow-up', count: 325 },
    { type: 'Procedure', count: 115 },
    { type: 'Test', count: 75 },
    { type: 'Emergency', count: 45 },
  ],
  recentAppointments: appointments.slice(0, 5),
};